### ISSUE TITLE
Links with <a href=""> incorrect

### ISSUE THREAD

**Issue by garazdawi** [adoptingerlang/adoptingerlang#62]
It seems like all/many the links with `<a href="">` are incorrect. For example the link to systools in: https://adoptingerlang.org/docs/production/docker/#multi-stage-build

I think they should be `[[link][target]]` or something like that.

**Comment by tsloughter** [comment]
Na, annoyingly, the alert block we use there does not go through the org-mode or markdown parsing. I haven't bothered to find a way to make a Hugo shortcode for it that works as org-mode/markdown instead of straight html, I probably should try.

**Comment by tsloughter** [comment]
You'll see on the rendered page it is a link https://adoptingerlang.org/docs/production/docker/#multi-stage-build

**Comment by garazdawi** [comment]
I end up here: https://adoptingerlang.org/docs/production/docker/%3Chttp://erlang.org/doc/man/systools.html#make%5Ftar-1%3E which is a 404.

**Comment by tsloughter** [comment]
ooooh, thanks, so not an issue with the use of anchors its the actual href. The damn shortcode also escapes shit, which is why we don't have `_`'s in those blocks but have to use the hex equivalent. 

I'll get this fixed.

**Comment by tsloughter** [comment]
For some reason using single quotes instead of double fixes it. Thanks again for pointing this out.
