### ISSUE TITLE
Running database migrations?

### ISSUE THREAD

**Issue by vais** [adoptingerlang/adoptingerlang#76]
There's a reference in the Releases chapter to `docker-compose up` running database migrations, but this is never revisited later in the chapter nor in the next chapter dedicated to Docker.

Is this something that's in the works? It would be really helpful! The topic of database migrations in the context of Docker and "the cloud" in general is not getting enough attention in any of the deployment tutorials I was able to find. I.e. what are some of the "best practices" around this? In the context of a single container deployment? What about multiple containers? Should migrations be run on start-up by the application itself vs delegated to external tools? Etc. etc.

Thanks again for writing this book!

**Comment by tsloughter** [comment]
@vais yes, it is covered more in the Kubernetes chapter that is in the works and should be out in the coming weeks. It will also be covered in a chapter on testing in the Developemet part of the booksite.

**Comment by vais** [comment]
@tsloughter awesome, thanks, looking forward!
