### ISSUE TITLE
Broken link on OTP Applications page

### ISSUE THREAD

**Issue by Jarak-Jakar** [adoptingerlang/adoptingerlang#79]
On the Development/OTP Applications page, the URL for the "Next" link at the bottom of the page appears to be incorrect.  When I click on it, I'm sent to a 404 page.  Clicking on the link for the following page listed in the Contents at the left-hand side of the page works fine, however.

It looks like the offending hyperlink doesn't point into the Development folder.  Compare the broken one: https://adoptingerlang.org/docs/supervision_trees to the working one: https://adoptingerlang.org/docs/development/supervision_trees/ (both taken from https://adoptingerlang.org/docs/development/otp_applications/)

**Comment by tsloughter** [comment]
Thanks, fixed in #80
